### ISSUE TITLE
getPostList Error

### ISSUE THREAD

**Issue by MiftahFA** [Supriyanto6543/flutter_social_media_clean_code#1]
Muncul error ketika klik Lihat Post. type 'Null' is not a subtype of type 'String'.
<img width="1680" alt="Screenshot 2024-05-12 at 22 28 04" src="https://github.com/Supriyanto6543/flutter_social_media_clean_code_cubit/assets/61034899/4e2413c3-410f-40e9-982c-6f8614a11e2a">

**Comment by Supriyanto6543** [comment]
tambahkan null safety pada model json yang terjadi error seperti ini ya -> ?? '';

**Comment by MiftahFA** [comment]
Siap makasih bang, sudah bisa
